version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./chroma:/app/chroma
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped